### ISSUE TITLE
Understanding the outcomes of Google Summer of Code

### ISSUE THREAD

**Issue by j3ffsilva** [pradeeban/tcia_swagger#1]
Dear Pradeeban Kathiravelu,

I am a Ph.D. student at the University of São Paulo (Brazil). We would like to understand how and how much Open Source Communities benefit from participating in Google Summer of Code (GSoC). We believe that your experience in GSoC is valuable and could help us achieve that. In a 1-minute questionnaire, we would like to know:

Concerning the project entitled "Data Federation / Integration Tools" developed in GSoC 2015.

1. Do you have a GitHub repository for the GSoC project? If so, could you provide us with the link to the project?

2. Have you continued committing code or opening issues to the GSoC project after GSoC? (Yes / No) If so, code, issues or both?

3. Have you continued committing code or opening issues to other OSS projects after GSoC? (Yes / No) If so, code, issues or both?

4. Could we use aggregate data from your participation in GSoC and other OSS projects in our research?

The following link contains a sample of our work and how we would use your data:
https://ieeexplore.ieee.org/document/8094410/

Regards,

Jefferson

**Comment by pradeeban** [comment]
Hi Jefferson,
Answers below:
[1] https://github.com/pradeeban/datacafe for GSoC 2015

[2] Yes, both

[3] Yes, both

[4] Yes, I have been a GSoC student 4 times (Abiword/2009, OMII-UK/2010, Emory/2014, and Emory 2015) and mentor 4 times (Abiword/2011, Abiword/2012, Abiword/2013, and Emory/2016).

I am a final year Ph.D. student myself, and some of my GSoC publications
[1] https://link.springer.com/article/10.1007%2Fs10619-018-7248-y (GSoC 2014 and GSoC 2015)
[2] https://link.springer.com/chapter/10.1007/978-3-319-67186-4_2 (GSoC 2014 and GSoC 2016)
[3] https://link.springer.com/chapter/10.1007/978-3-319-57741-8_7 (GSoC 2015)

Good luck with your research.
I hope I have answered your questions adequately. If you have updates or comments, please contact me via email at kk.pradeeban -AT- gmail.com.

I am closing this issue as this is a topic irrelevant to the tcia_swagger APIs.
